account/urls.py
from django.urls import path
from account import views


app_name = 'account'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('registration/', views.registration_page, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns = [
    path("create_room/", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

home/urls.py
from django.urls import path
from home import views


app_name = 'home'

urlpatterns = [
    path('', views.home_page, name='home'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('ticket/', include('ticket.urls')),
    path('chat/', include('chat.urls')),
]


# static file settings
if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/views.py
from django.shortcuts import render

# Create your views here.
def home_page(request):

    html_template_name = 'home/home.html'
    context = {}
    return render(request, html_template_name, context)

templates/home/home.html
{% extends 'index.html' %}
{% block title %} Home {% endblock %}
{% load static %}



{% block content %}

    <section class="home">
        <div class="container">
            <div class="home__text text-center">
                {% if user.is_authenticated %}
                <h1>Hello, {{user.full_name}} </h1>
                {% endif %}
               <h1>Welcome to Customer Support Ticketing System</h1>
            </div>

            <div class="home__login text-center">
                {% if not user.is_authenticated %}
                    <a href="{% url 'account:login' %}">Login</a>
                    <span class="home__subtext">. don't have an account?</span>
                    <a href="{% url 'account:register' %}">Register</a>
                {% endif %}
            </div>


            {% if user.is_authenticated %}
            <div class="chat__head">
                <a class="btn btn-success" href="{% url 'chat:index' %}">Chat</a>
            </div>
            {% endif %}

        </div>
    </section>

{% endblock %}