account/urls.py
from django.urls import path
from account import views


app_name = 'account'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('registration/', views.registration_page, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns = [
    path("create_room/", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

home/urls.py
from django.urls import path
from home import views


app_name = 'home'

urlpatterns = [
    path('', views.home_page, name='home'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('ticket/', include('ticket.urls')),
    path('chat/', include('chat.urls')),
]


# static file settings
if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/urls.py
from django.urls import path
from ticket import views


app_name = 'ticket'

urlpatterns = [
    path('create/<str:username>/', views.creating_ticket, name='create_ticket'),
    path('ticket_list/<str:username>/', views.ticket_page, name='ticket_page'),
    path('edit_ticket/<int:ticket_id>/', views.update_ticket, name='ticket_update'),
    path('delete/<int:ticket_id>/', views.delete_ticket, name='delete'),
    path('success/', views.success_page, name='success'),
    path('updated/', views.update_success, name='updated'),
    path('comments/<int:ticket_id>/', views.comment_page, name='comment'),
    path('admin_action/', views.admin_ticket_page, name='admin_ticket'),
]

templates/base/footer.html
 {% load static %}

<footer>
    <div class="container text-center">
        <div class="footer__copyright">
            Copyright &copy;<script>document.write(new Date().getFullYear());</script>. All rights reserved
        </div>
    </div>
</footer>

 
 
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>
</html>

templates/base/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ticketing System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>


    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container container-fluid">
                <a class="navbar-brand" href="{% url 'home:home' %}">Ticketing System</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
                        </li>
                        
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ticket:create_ticket' user.username %}">Open Ticket</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ticket:ticket_page' user.username %}">My Tickets</a>
                        </li>
                        {% endif %}

                        {% if user.is_authenticated and user.is_admin %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'ticket:admin_ticket' %}">All Tickets</a>
                            </li>
                        {% endif %}
            
                    </ul>

                    <span class="navbar-text">
                        {% if not user.is_authenticated %}
                        <a class="nav-link" href="{% url 'account:login' %}">Login</a>
                        {%else %}
                        <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
                        {% endif %}
                    </span>

                </div>
            </div>
        </nav>
    </header>
    