chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns = [
    path("create_room/", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('ticket/', include('ticket.urls')),
    path('chat/', include('chat.urls')),
]


# static file settings
if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/urls.py
from django.urls import path
from ticket import views


app_name = 'ticket'

urlpatterns = [
    path('create/<str:username>/', views.creating_ticket, name='create_ticket'),
    path('ticket_list/<str:username>/', views.ticket_page, name='ticket_page'),
    path('edit_ticket/<int:ticket_id>/', views.update_ticket, name='ticket_update'),
    path('delete/<int:ticket_id>/', views.delete_ticket, name='delete'),
    path('success/', views.success_page, name='success'),
    path('updated/', views.update_success, name='updated'),
    path('comments/<int:ticket_id>/', views.comment_page, name='comment'),
    path('admin_action/', views.admin_ticket_page, name='admin_ticket'),
]

ticket/models.py
from django.db import models
from account.models import UserAccount

# Create your models here.
class createTicket(models.Model):
    user_account = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()

    CATEGORY_CHOICES = [
    ('technical', 'Technical'),
    ('billing', 'Billing'),
    ('general', 'General'),
    ('others', 'Others'),
    ]

    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)

    PRIORITY_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
    ]

    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES)

    uploaded_file = models.FileField(upload_to='upload/', null=True, blank=True)

    TICKET_STATUS = [
        ('open', 'Open'),
        ('progress', 'In Progress'),
        ('resolved', 'Resolved'),
        ('closed', 'Closed'),
    ]

    status = models.CharField(max_length=20, choices=TICKET_STATUS, default='open')

    create_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title







class CommentModel(models.Model):
    user_info = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
    ticket_no = models.IntegerField()
    message = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message
    
     

ticket/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ticket.form import TicketForm, UpdateTicketForm, CommentForm
from ticket.models import createTicket, CommentModel
from account.models import UserAccount

# Create your views here.
def creating_ticket(request, username):
    
    html_template_name = 'ticket/open.html'
    
    get_user = UserAccount.objects.get(username=username)

    if request.method == 'POST':
        ticket_form = TicketForm(request.POST, request.FILES)

        if ticket_form.is_valid():
            title = ticket_form.cleaned_data['title']
            description = ticket_form.cleaned_data['description']
            category = ticket_form.cleaned_data['category']
            priority = ticket_form.cleaned_data['priority']
            uploaded_file = None

            if ticket_form.cleaned_data['uploaded_file']:
                uploaded_file = ticket_form.cleaned_data['uploaded_file']
        
        

            ticket = createTicket.objects.create(
                title = title,
                description = description,
                category = category,
                priority = priority,
                uploaded_file = uploaded_file
            )
            ticket.user_account = get_user      
            ticket.save()

        return redirect('ticket:success')

    else:
        ticket_form = TicketForm()


    context = {
        'form': ticket_form,
    }

    return render(request, html_template_name, context)





def update_ticket(request, ticket_id):

    html_template_name = 'ticket/edit.html'

    get_ticket_id = ticket_id
    get_ticket = get_object_or_404(createTicket, pk=ticket_id)
    edit_form = UpdateTicketForm(instance=get_ticket) 

    if request.method == 'POST':
            
        edit_form = UpdateTicketForm(request.POST, request.FILES, instance=get_ticket)

        if edit_form.is_valid():
            update_form = edit_form.save(commit=False)
            update_form.save()

            return redirect('ticket:updated')

        else:
            edit_form = UpdateTicketForm(instance=get_ticket) 

    context = {
        'form': edit_form,
        'id_ticket': get_ticket_id,
    }

    return render(request, html_template_name, context)





def update_success(request):

    html_template_name = 'ticket/updated.html'
    context = {}
    return render(request, html_template_name, context)





def ticket_page(request, username):

    html_template_name = 'ticket/ticket.html'

    get_tickets = createTicket.objects.filter(user_account__username=username).all()

    context = {
        'ticket_info': get_tickets,
    }

    return render(request, html_template_name, context)






def delete_ticket(request, ticket_id):

    get_ticket = createTicket.objects.get(pk=ticket_id)
    get_ticket.delete()

    return redirect('home:home')
    





def success_page(request):

    html_template_name = 'ticket/success.html'

    context = {}

    return render(request, html_template_name, context) 






def comment_page(request, ticket_id):

    html_template_name = 'ticket/comment.html'

    ticket_value = ticket_id

    get_comment = CommentModel.objects.filter(ticket_no=ticket_id)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment = comment_form.cleaned_data['message']

            save_comment = CommentModel.objects.create(
                user_info = request.user,
                ticket_no = ticket_id,
                message = comment,
            )

            comment_form = CommentForm()

            save_comment.save()

    else:
        comment_form = CommentForm()

    context = {
        'form': comment_form,
        'id_ticket': ticket_value,
        'comments' : get_comment,
    }

    return render(request, html_template_name, context)




def admin_ticket_page(request):

    html_template_name = 'ticket/all.html'

    all_tickets = createTicket.objects.all()

    context = {
        'ticket_info': all_tickets,
    }

    return render(request, html_template_name, context)

templates/ticket/all.html
{% extends 'index.html' %}
{% block title %}All Tickets {% endblock %}
{% load static %}



{% block content %}

    <section class="ticket_list">
        <div class="container">

            {% if user.is_authenticated and user.is_admin %}
            {% for item in ticket_info %}
            <div class="card mt-3 mb-3">
                <div class="card-body">
                    <div class="ticket">
                        <strong>ID: {{ item.id }}</strong>
                        <h1>{{ item.title }}</h1>
                        <p>{{ item.description }}</p>
                        {% if item.uploaded_file %}
                            <span>Attachment: </span><a href="{{ item.uploaded_file.url }}">{{ item.uploaded_file.url }}</a>
                        {% else %}
                            <p>Attachment: No</p>
                        {% endif %}   
                    </div>

                    <div class="mt-3 mb-3">
                        <h5>Category: {{ item.category }}</h5>
                        <h5>Priority: {{ item.priority }}</h5>
                        <span>Status: {{ item.status }}</span>
                    </div>

                    <div class="user__info mt-3 mb-3">
                        <p>Posted by: {{ item.user_account.username }}</p>
                        <span>{{ item.create_at }}</span>
                    </div>
                
                    <div class="ticket__btn mt-3 mb-3">
                        <a href="{% url 'ticket:comment' item.pk %}" class="btn btn-primary">Comment</a>
                        <a href="{% url 'ticket:ticket_update' item.pk %}" class="btn btn-success">Edit</a>
                        <a href="{% url 'ticket:delete' item.pk %}" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </div>
            {% endfor %}

            {% else %}
             <div class="card mt-3 mb-3">
                <div class="card-body">
                    <div class="ticket">
                        <span>No Ticket Found</span>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </section>

{% endblock %}

templates/ticket/comment.html
{% extends 'index.html' %}
{% block title %} Comments {% endblock %}
{% load static %}



{% block content %}

    <section class="comment">
        <div class="container pt-3 mb-3">
            <h1 class="text-center">Comments</h1>
        

        {% if comments %}
        <div class="comment__main">
            {% for item in comments %}
                <div class="card mt-3 mb-3">
                    <div class="card-body">
                        <div class="comment__content">
                            <h3 class="text-center">{{ item.message }}</h3>
                        </div>

                        <div class="comment__user">
                            <h5>{{ item.user_info.username }}</h5><span>{{ item.created_at }}</span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        {% else %}

        <div class="card">
            <div class="card-body">
                <h3>NO Comments Found</h3>
            </div>
        </div>

        {% endif %}


        <div class="form__container mt-3 mb-3">
            <form action="{% url 'ticket:comment' id_ticket %}" method="POST">
                {% csrf_token %}
                
                <div class="mb-3 pt-3">
                    {{ form.message }}
                </div>

                <button type="submit" class="btn btn-primary">Comment</button>
            </form>
        </div>

        </div>
    </section>

{% endblock %}

templates/ticket/edit.html
{% extends 'index.html' %}
{% block title %} Edit Ticket {% endblock %}
{% load static %}



{% block content %}

    <section class="open_ticket">
        <div class="container text-center pt-3 mb-3">
            <h1>Create a Ticket</h1>
        </div>

        <div class="form__container">
            <form action="{% url 'ticket:ticket_update' id_ticket %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3 pt-3">
                    <label for="subject" class="form-label">Edit Ticket Subject</label>
                    {{ form.title }}

                <div class="mb-3 pt-3">
                    <label for="description" class="form-label">Edit Ticket Description</label>
                    {{ form.description }}
                </div>

                <div class="form-group pt-3 mb-3">
                    <label for="{{ form.category.id_for_label }}">Category:</label>
                        {{ form.category }}
                </div>

                <div class="form-group pt-3 mb-3">
                    <label for="{{ form.priority.id_for_label }}">Priority:</label>
                        {{ form.priority }}
                </div>

                <div class="mb-3 pt-3">
                    <label for="file" class="form-label">Attachment (if any)</label>
                    {{ form.uploaded_file }}
                </div>

                <button type="submit" class="btn btn-primary">Edit</button>
            </form>
        </div>
    </section>

{% endblock %}

templates/ticket/open.html
{% extends 'index.html' %}
{% block title %} Home {% endblock %}
{% load static %}



{% block content %}

    <section class="open_ticket">
        <div class="container text-center pt-3 mb-3">
            <h1>Create a Ticket</h1>
        </div>

        <div class="form__container">
            <form action="" method="">
                <div class="mb-3 pt-3">
                    <label for="subject" class="form-label">Ticket Subject</label>
                    <input type="text" class="form-control" id="subject" name="subject" required>

                <div class="mb-3 pt-3">
                    <label for="description" class="form-label">Ticket Description</label>
                    <input type="text" class="form-control" id="description" name="description" required>
                </div>

                <select class="form-select pt-3 mb-3" aria-label="Default select example" required>
                    <option value="" disabled selected>Select Category</option>
                    <option value="1">Technical</option>
                    <option value="2">Billing</option>
                    <option value="3">General</option>
                    <option value="4">Others</option>
                </select>

                <select class="form-select pt-3 mb-3" aria-label="Default select example" required>
                    <option value="" disabled selected>Priority</option>
                    <option value="1">Low</option>
                    <option value="2">Medium</option>
                    <option value="3">High</option>
                </select>

                <div class="mb-3 pt-3">
                    <label for="file" class="form-label">Attachment (if any)</label>
                    <input class="form-control" type="file" id="file" name="file">
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </section>

{% endblock %}

templates/ticket/success.html
{% extends 'index.html' %}
{% block title %} Success {% endblock %}
{% load static %}



{% block content %}

    <section class="ticket_list">
        <div class="container">
            <div class="success__text text-center">
                <h1>Ticket submitted successfully</h1>
            </div>
        </div>
    </section>

{% endblock %}

templates/ticket/ticket.html
{% extends 'index.html' %}
{% block title %} Tickets {% endblock %}
{% load static %}



{% block content %}

    <section class="ticket_list">
        <div class="container">

            {% if user.is_authenticated and ticket_info %}
            {% for item in ticket_info %}
            <div class="card mt-3 mb-3">
                <div class="card-body">
                    <div class="ticket">
                        <h1>{{ item.title }}</h1>
                        <p>{{ item.description }}</p>
                        {% if item.uploaded_file %}
                            <span>Attachment: </span><a href="{{ item.uploaded_file.url }}">{{ item.uploaded_file.url }}</a>
                        {% else %}
                            <p>Attachment: No</p>
                        {% endif %}   
                    </div>

                    <div class="mt-3 mb-3">
                        <h5>Category: {{ item.category }}</h5>
                        <h5>Priority: {{ item.priority }}</h5>
                        <span>Status: {{ item.status }}</span>
                    </div>

                    <div class="user__info mt-3 mb-3">
                        <p>Posted by: {{ item.user_account.username }}</p>
                        <span>{{ item.create_at }}</span>
                    </div>
                
                    <div class="ticket__btn mt-3 mb-3">
                        <a href="{% url 'ticket:comment' item.pk %}" class="btn btn-primary">Comment</a>
                        <a href="{% url 'ticket:ticket_update' item.pk %}" class="btn btn-success">Edit</a>
                        <a href="{% url 'ticket:delete' item.pk %}" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </div>
            {% endfor %}

            {% else %}
             <div class="card mt-3 mb-3">
                <div class="card-body">
                    <div class="ticket">
                        <span>No Ticket Found</span>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </section>

{% endblock %}

templates/ticket/updated.html
{% extends 'index.html' %}
{% block title %} Updated {% endblock %}
{% load static %}



{% block content %}

    <section class="ticket_list">
        <div class="container">
            <div class="success__text text-center">
                <h1>Ticket Updated successfully</h1>
            </div>
        </div>
    </section>

{% endblock %}